app = 'website-holy-haze-9007'
kill_signal = 'SIGINT'
kill_timeout = 5

[env]
PORT = '8080'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true

[[http_service.checks]]
interval = '10s'
timeout = '2s'
grace_period = '5s'